### ISSUE TITLE
[Bug] Open device view crashes

### ISSUE THREAD

**Issue by Simon-Laux** [garredow/kaiware#20]
<img width="400" alt="Screenshot 2021-12-12 at 23 07 19" src="https://user-images.githubusercontent.com/18725968/145731436-75d71c00-5945-4d61-a3f9-127ad9fa6fcb.png">

<img width="810" alt="Screenshot 2021-12-12 at 23 07 00" src="https://user-images.githubusercontent.com/18725968/145731424-5799ab8d-1f60-4a2e-bf87-0906b6869468.png">

<details>
<summary>as text</summary>

```
DevicePanel.tsx?ef9c:98 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at eval (DevicePanel.tsx?ef9c:98)
    at Array.map (<anonymous>)
    at DevicePanel (DevicePanel.tsx?ef9c:93)
    at renderWithHooks (react-dom.development.js?f731:14985)
    at updateFunctionComponent (react-dom.development.js?f731:17356)
    at beginWork (react-dom.development.js?f731:19063)
    at HTMLUnknownElement.callCallback (react-dom.development.js?f731:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?f731:3994)
    at invokeGuardedCallback (react-dom.development.js?f731:4056)
    at beginWork$1 (react-dom.development.js?f731:23964)
eval @ DevicePanel.tsx?ef9c:98
DevicePanel @ DevicePanel.tsx?ef9c:93
renderWithHooks @ react-dom.development.js?f731:14985
updateFunctionComponent @ react-dom.development.js?f731:17356
beginWork @ react-dom.development.js?f731:19063
callCallback @ react-dom.development.js?f731:3945
invokeGuardedCallbackDev @ react-dom.development.js?f731:3994
invokeGuardedCallback @ react-dom.development.js?f731:4056
beginWork$1 @ react-dom.development.js?f731:23964
performUnitOfWork @ react-dom.development.js?f731:22779
workLoopSync @ react-dom.development.js?f731:22707
renderRootSync @ react-dom.development.js?f731:22670
performSyncWorkOnRoot @ react-dom.development.js?f731:22293
eval @ react-dom.development.js?f731:11327
unstable_runWithPriority @ scheduler.development.js?c398:468
runWithPriority$1 @ react-dom.development.js?f731:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?f731:11322
flushSyncCallbackQueue @ react-dom.development.js?f731:11309
scheduleUpdateOnFiber @ react-dom.development.js?f731:21893
dispatchAction @ react-dom.development.js?f731:16139
eval @ DevicePanel.tsx?ef9c:35
step @ DevicePanel.tsx:52
eval @ DevicePanel.tsx:33
fulfilled @ DevicePanel.tsx:24
Promise.then (async)
step @ DevicePanel.tsx:26
fulfilled @ DevicePanel.tsx:24
Promise.then (async)
step @ DevicePanel.tsx:26
fulfilled @ DevicePanel.tsx:24
Promise.then (async)
step @ DevicePanel.tsx:26
eval @ DevicePanel.tsx:27
__awaiter @ DevicePanel.tsx:23
getData @ DevicePanel.tsx?ef9c:25
eval @ DevicePanel.tsx?ef9c:40
invokePassiveEffectCreate @ react-dom.development.js?f731:23487
callCallback @ react-dom.development.js?f731:3945
invokeGuardedCallbackDev @ react-dom.development.js?f731:3994
invokeGuardedCallback @ react-dom.development.js?f731:4056
flushPassiveEffectsImpl @ react-dom.development.js?f731:23574
unstable_runWithPriority @ scheduler.development.js?c398:468
runWithPriority$1 @ react-dom.development.js?f731:11276
flushPassiveEffects @ react-dom.development.js?f731:23447
eval @ react-dom.development.js?f731:23324
workLoop @ scheduler.development.js?c398:417
flushWork @ scheduler.development.js?c398:390
performWorkUntilDeadline @ scheduler.development.js?c398:157
react-dom.development.js?f731:20085 The above error occurred in the <DevicePanel> component:

    at DevicePanel (webpack-internal:///./src/components/DevicePanel.tsx:84:22)
    at div
    at View (webpack-internal:///./src/ui-components/view/View.tsx:11:36)
    at Device (webpack-internal:///./src/routes/Device.tsx:28:45)
    at ErrorBoundary (webpack-internal:///./src/components/ErrorBoundery.tsx:27:28)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:448:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:650:29)
    at ErrorBoundary (webpack-internal:///./src/components/ErrorBoundery.tsx:27:28)
    at div
    at App (webpack-internal:///./src/App.tsx:63:55)
    at PanelsProvider (webpack-internal:///./src/contexts/PanelsProvider.tsx:49:35)
    at DeviceProvider (webpack-internal:///./src/contexts/DeviceProvider.tsx:69:35)
    at SettingsProvider (webpack-internal:///./src/contexts/SettingsProvider.tsx:54:35)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:38:21)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:79:30)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:102:35)
    at ErrorBoundary (webpack-internal:///./src/components/ErrorBoundery.tsx:27:28)
    at AppWrapper

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

</details>

**Comment by garredow** [comment]
May have been fixed with https://github.com/garredow/kaiware/commit/89c41391eedc5bffd61d8104cfbad2a6b0862452. Please verify. Thanks!

**Comment by Simon-Laux** [comment]
thanks that fixed it
